version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  inmemory:  # This driver takes no parameters
  delete:
    enabled: false
  redirect:
    disable: false
  cache:
    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: true
      age: 8736h # 1 year
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: localhost:5000
  relativeurls: false
  tls:
    certificate: /path/to/x509/public #TODO: Get proper CA-certs here
    key: /path/to/x509/private 
  debug:
    addr: localhost:5001
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: false
redis:
  addr: localhost:6379
  db: 0
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
compatibility:
  schema1:
    signingkeyfile: /etc/registry/key.json