version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  inmemory:  # This driver takes no parameters
  delete:
    enabled: false
  redirect:
    disable: false
  cache:
    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: true
      age: 8736h # 1 year
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: localhost:443
  relativeurls: false
  tls:
    certificate: /certs/registry.crt #TODO: Get proper CA-certs here
    key: /certs/registry.key 
  debug:
    addr: localhost:5001
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: false
